# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activesupport', '~> 6.1'
gem 'faraday', '~> 1.1'
gem 'sinatra'
gem 'rack-cors'


group :development, :test do
  gem 'byebug'
  gem 'dotenv'
end

group :test do
  gem 'rack-test'
  gem 'rspec'
  gem 'vcr'
  gem 'webmock'
end
